In [1]:
import argparse
from utils import split_events
from dt_converter import Converter

/home/atehort/miniconda3/envs/coffea_env/lib/python3.10/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector

In [5]:
"""parser = argparse.ArgumentParser(description="Run the converter with given path to the .root file.")
parser.add_argument("--path", 
                    type=str, 
                    help="Path to the .root file.")
parser.add_argument("--label", 
                    type=str, 
                    help="Label to save the output file.")
parser.add_argument("--output_path", 
                    type=str, 
                    help="Path to the output file.")
parser.add_argument("--file_type", 
                    type=str, 
                    default="parquet",
                    help="Type of the output file.")
args = parser.parse_args()"""

root_path = "/store/user/atehort/Signal_VBF_2Jets_4MuonsRun_24_01_25_Events/Run_1/Run_1/tag_1_delphes_events.root"#args.path
label = "test"#args.label
output_path = "."#args.output_path
file_type = "parquet"#args.file_type
jet_multiplicity = 2
e_mu_multiplicity = 2

tree_test = Converter(root_path)
tree_test.generate({"Jet": ["PT", "Eta", "Phi", "Mass"],
                    "Muon": ["PT", "Eta", "Phi", "Charge"],
                    "Electron": ["PT", "Eta", "Phi", "Charge"],
                    "MissingET": ["MET", "Phi"]}, 
                    jet_elements = jet_multiplicity, e_mu_elements = e_mu_multiplicity)
df = tree_test.df
df = df.loc[~ df[f"muon_pt{e_mu_multiplicity - 1}"].isna()]
df.reset_index(drop = True, inplace = True)
df

#split_events(df, label, output_path, file_type)

,jet_pt0,jet_pt1,jet_eta0,jet_eta1,jet_phi0,jet_phi1,jet_mass0,jet_mass1,muon_pt0,muon_pt1,...,electron_pt0,electron_pt1,electron_eta0,electron_eta1,electron_phi0,electron_phi1,electron_charge0,electron_charge1,missinget_met,missinget_phi
0,189.224380,38.928253,-1.473494,2.040997,2.798561,-1.789124,16.528381,4.054944,62.674671,35.817379,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.961361,-0.013043
1,238.576477,43.281029,-1.594624,0.877332,3.058456,-0.401406,31.668911,6.907176,77.726845,47.932529,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.867574,-2.283789
2,231.035065,93.950409,0.881956,-3.930154,0.277717,-2.223021,29.565239,18.087618,86.855232,47.127281,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.530766,-0.003098
3,218.794189,84.371452,-2.627675,-0.440456,2.509853,-1.728934,21.195507,10.087935,76.803055,73.265053,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.742084,-1.143201
4,73.119850,59.720551,-3.453642,-3.046286,-1.482899,-0.787964,13.408684,10.200015,67.987396,45.386929,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.086243,-0.472432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49146,158.409943,99.769432,2.723663,-3.202695,0.106409,1.932674,9.917507,5.566621,79.380066,54.508186,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.219212,-0.040643
49147,93.744080,53.407234,2.846453,-4.031807,2.522307,1.982592,7.212959,13.175215,87.042679,41.615856,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.580904,-3.130403
49148,95.663147,NaN,3.283185,NaN,2.276191,NaN,11.038764,NaN,75.251938,40.903957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.338257,2.819930
49149,60.628147,31.345276,0.399715,3.706862,1.624512,1.995198,9.425628,2.805975,40.017601,37.550220,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.774929,0.646812
49150,156.871048,62.318127,-2.014024,4.296378,1.119083,0.568446,27.963692,4.303282,87.299637,68.826447,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.051811,0.790095

In [3]:
df.columns

Index(['jet_pt0', 'jet_pt1', 'jet_pt2', 'jet_pt3', 'jet_eta0', 'jet_eta1',
       'jet_eta2', 'jet_eta3', 'jet_phi0', 'jet_phi1', 'jet_phi2', 'jet_phi3',
       'jet_mass0', 'jet_mass1', 'jet_mass2', 'jet_mass3', 'muon_pt0',
       'muon_pt1', 'muon_eta0', 'muon_eta1', 'muon_phi0', 'muon_phi1',
       'muon_charge0', 'muon_charge1', 'electron_pt0', 'electron_pt1',
       'electron_eta0', 'electron_eta1', 'electron_phi0', 'electron_phi1',
       'electron_charge0', 'electron_charge1', 'missinget_met',
       'missinget_phi'],
      dtype='object')